In [1]:
import pandas as pd
from pycaret.regression import *

In [2]:
df = pd.read_csv("/Users/priyakundu/Downloads/Short_Final_Executed_Data.csv")

In [3]:
regression_setup = setup(data = df, target='Price', train_size=0.7)

In [4]:
best = compare_models()

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

In [5]:
predictions = predict_model(best, data=df)