In [1]:
import pandas as pd
from pycaret.regression import *

In [4]:
df = pd.read_csv("/Users/priyakundu/Downloads/Long_Final_Executed_Data.csv")

In [5]:
regression_setup = setup(data = df, target='Price', train_size=0.7)

In [6]:
best = compare_models()

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

In [8]:
predictions = predict_model(best, data=df)